service: slack-budget

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-2
  deploymentBucket: axkz-serverless-deployments
  stackTags:
    project: serverless
    service: ${self:service}

  iamRoleStatements:
  - Effect: "Allow"
    Action:
      - "dynamodb:GetItem"
    Resource: 
      Fn::Join:
        - ":"
        - - "arn"
          - "aws"
          - "dynamodb"
          - Ref: AWS::Region
          - Ref: AWS::AccountId
          - "table/budget"

functions:
  budgetReport:
    handler: src/reportBudgetHandler.reportBudget
    name: report-budget
    description: Handle reporting of budget DynamoDB table
    reservedConcurrency: 1
    environment:
      SLACK_INCOMING_WEBHOOK_URL: TBD
      SLACK_INCOMING_WEBHOOK_CHANNEL: TBD
      SLACK_INCOMING_WEBHOOK_USER: TBD

resources:
  Resources:
    SlackBudget:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: budget
        AttributeDefinitions:
          - AttributeName: window
            AttributeType: S
          - AttributeName: category
            AttributeType: S
        KeySchema:
          - AttributeName: window
            KeyType: HASH
          - AttributeName: category
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    