service: slack-budget

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-2
  deploymentBucket: axkz-serverless-deployments
  stackTags:
    project: budget
    use: personal

  iamRoleStatements:
  - Effect: "Allow"
    Action:
      - "dynamodb:Query"
      - "dynamodb:UpdateItem"
    Resource: 
      Fn::Join:
        - ":"
        - - "arn"
          - "aws"
          - "dynamodb"
          - Ref: AWS::Region
          - Ref: AWS::AccountId
          - "table/budget"

functions:
  budgetReport:
    handler: src/reportBudgetHandler.reportBudget
    name: report-budget
    description: Handle reporting of current month's budget
    reservedConcurrency: 1
    environment:
      SLACK_URL: TBD
      SLACK_CHANNEL: TBD

  budgetAddCategoryExpense:
    handler: src/addExpenseBudgetHandler.addBudgetCategoryExpense
    name: add-budget-category-expense
    description: Adds a single expense entry to a budget category for the current month
    reservedConcurrency: 1
    environment:

resources:
  Resources:
    SlackBudget:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: budget
        AttributeDefinitions:
          - AttributeName: timeframe
            AttributeType: S
          - AttributeName: category
            AttributeType: S
        KeySchema:
          - AttributeName: timeframe
            KeyType: HASH
          - AttributeName: category
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    