openapi: 3.0.0
info:
  title: AxKz Budget API
  description: API to interact with the Slack Budget tool
  version: 0.0.1
paths:
  /slack/report:
    get:
      summary: Report budget in Slack blocks format
      description: Report budget in Slack blocks format
      responses:
        '200': 
          description: Confirmation that the report was submitted to Slack